#!/bin/bash

# Copyright 2013 Telefonica Investigación y Desarrollo, S.A.U
# 
# This file is part of FIGWAY software (a machine2machine gateway for the Raspberry PI).
#
# FIGWAY is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# FIGWAY is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along with FIGWARE. If not, see http://www.gnu.org/licenses/.
#
# For those usages not covered by the GNU Affero General Public License please contact with: Carlos Ralli Ucendo [ralli@tid.es] 


# Developed by Carlos Ralli Ucendo (@carlosralli), Aug 2013.
#
# This script registers z-wave devices listed below into FI-WARE M2M Backend platform The M2M platform and related protocol are 
# specified in the figway configuration file.
# Currently It does not use z-way JSON/C APIs to discover z-wave devices but your manual configuration input below. 
# In the future this tool should be re-coded to use the above mentioned z-way APIs.

#########################################################################################
#### This is the place to configure the z-wave devices
#### If more devices are added you may need to uncomment/add new sections below
#########################################################################################

DEV_4IN1=2
DEV_KEY=3
DEV_SWITCH=4
DEV_RGBS=5

DEV_GARAGE=256 
DEV_DOOR=257 
DEV_SWITCH2=258

#########################################################################################
#### This section calculates DEV_ID codes (left padding with Zero to get 4 char ID)
#### If more devices are added in the previous section, be sure to calculate IDs     
#########################################################################################

DEV_4IN1_ID=$(printf %04d $DEV_4IN1) 
DEV_KEY_ID=$(printf %04d $DEV_KEY)
DEV_SWITCH_ID=$(printf %04d $DEV_SWITCH)

DEV_GARAGE_ID=$(printf %04d $DEV_GARAGE)
DEV_DOOR_ID=$(printf %04d $DEV_DOOR)
DEV_RGBS_ID=$(printf %04d $DEV_RGBS)
DEV_SWITCH2_ID=$(printf %04d $DEV_SWITCH2)

#########################################################################################
#### Main Script below        
#########################################################################################

./registerDevice $DEV_4IN1_ID 4IN1
./registerDevice $DEV_KEY_ID KEY
./registerDevice $DEV_SWITCH_ID SWITCH 
./registerDevice $DEV_RGBS_ID RGBS

#./registerDevice $DEV_GARAGE_ID GARAGE 
#./registerDevice $DEV_DOOR_ID DOOR
#./registerDevice $DEV_SWITCH2_ID SWITCH
